# Generated by Django 4.2.5 on 2023-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_categories',
            field=models.ImageField(default='imagen.png', upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='imagen.png', upload_to='productos/'),
        ),
    ]
