# Generated by Django 4.2.5 on 2023-10-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_category_img_categories_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice',
            field=models.BooleanField(default=True),
        ),
    ]
