# Generated by Django 4.2.5 on 2023-10-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_invoice_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice',
            new_name='active',
        ),
    ]
