# Generated by Django 4.2.5 on 2023-10-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_rename_invoice_invoice_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
